apply plugin: 'com.android.application'

android {
    namespace 'id.my.duniamu.learnearn'
    compileSdk 34

    defaultConfig {
        applicationId "id.my.duniamu.learnearn"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // WAJIB: untuk generate BuildConfig
    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
